# Generated by Django 4.1.7 on 2023-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_uzytkownik_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='nr_telefonu',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
